# Generated by Django 4.0.5 on 2022-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfautomation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
