# Generated by Django 4.0.5 on 2022-06-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfautomation', '0002_alter_contacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
