# Generated by Django 4.0.5 on 2022-06-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfautomation', '0003_alter_contacts_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
