# Generated by Django 4.0.5 on 2022-06-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfautomation', '0004_alter_opportunity_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
